// <auto-generated />
namespace GestionFicha.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Migracionnum124022022 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migracionnum124022022));
        
        string IMigrationMetadata.Id
        {
            get { return "202202251334015_Migracion-num1-24-02-2022"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
